"""rescue offers, telemetry, sos, reputation

Adds the domain that was advertised but absent: the two-way rescue handshake
(rescue_offers), position and cargo-condition telemetry, derived alerts, SOS
with its broadcast audit, emergency contacts, and reputation earned from
recorded behaviour rather than asserted by the caller.

Revision ID: 0007_offers_telemetry_sos
Revises: 0006_escrow_ownership
Create Date: 2026-09-18 20:48:41.495981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0007_offers_telemetry_sos'
down_revision: Union[str, None] = '0006_escrow_ownership'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_reputation',
    sa.Column('company_id', sa.String(length=64), nullable=False),
    sa.Column('offers_received', sa.Integer(), server_default='0', nullable=False),
    sa.Column('offers_accepted', sa.Integer(), server_default='0', nullable=False),
    sa.Column('offers_declined', sa.Integer(), server_default='0', nullable=False),
    sa.Column('offers_expired', sa.Integer(), server_default='0', nullable=False),
    sa.Column('avg_response_seconds', sa.Float(), nullable=True),
    sa.Column('rescues_completed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rescues_cancelled_after_bind', sa.Integer(), server_default='0', nullable=False),
    sa.Column('disputes_raised_against', sa.Integer(), server_default='0', nullable=False),
    sa.Column('condition_breaches', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rating_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rating_sum', sa.Integer(), server_default='0', nullable=False),
    sa.Column('trust_score', sa.Float(), server_default='100.0', nullable=False),
    sa.Column('signals_json', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('emergency_contacts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('company_id', sa.String(length=64), nullable=False),
    sa.Column('driver_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('relationship', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('notify_on_sos', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emergency_contacts', schema=None) as batch_op:
        batch_op.create_index('ix_contacts_scope', ['company_id', 'driver_id'], unique=False)

    op.create_table('truck_live_state',
    sa.Column('truck_id', sa.String(length=64), nullable=False),
    sa.Column('company_id', sa.String(length=64), nullable=False),
    sa.Column('last_ping_id', sa.BigInteger(), nullable=True),
    sa.Column('last_recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('speed_kph', sa.Float(), nullable=True),
    sa.Column('heading_deg', sa.Float(), nullable=True),
    sa.Column('battery_pct', sa.Float(), nullable=True),
    sa.Column('is_charging', sa.Boolean(), nullable=True),
    sa.Column('is_moving', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('dwell_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dwell_anchor_lat', sa.Float(), nullable=True),
    sa.Column('dwell_anchor_lng', sa.Float(), nullable=True),
    sa.Column('last_temperature_c', sa.Float(), nullable=True),
    sa.Column('last_reading_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('truck_id')
    )
    with op.batch_alter_table('truck_live_state', schema=None) as batch_op:
        batch_op.create_index('ix_live_state_received', ['last_received_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_truck_live_state_company_id'), ['company_id'], unique=False)

    op.create_table('cargo_readings',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('shipment_id', sa.String(length=64), nullable=False),
    sa.Column('truck_id', sa.String(length=64), nullable=True),
    sa.Column('company_id', sa.String(length=64), nullable=False),
    sa.Column('incident_id', sa.String(length=64), nullable=True),
    sa.Column('sensor_id', sa.String(length=64), nullable=False),
    sa.Column('client_reading_id', sa.String(length=64), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('humidity_pct', sa.Float(), nullable=True),
    sa.Column('door_open', sa.Boolean(), nullable=True),
    sa.Column('reefer_state', sa.String(length=16), nullable=True),
    sa.Column('reefer_setpoint_c', sa.Float(), nullable=True),
    sa.Column('sensor_battery_pct', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=16), server_default='device', nullable=False),
    sa.Column('trust_level', sa.String(length=16), server_default='UNVERIFIED', nullable=False),
    sa.Column('is_backfill', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint('humidity_pct IS NULL OR humidity_pct BETWEEN 0 AND 100', name='chk_reading_humidity_range'),
    sa.CheckConstraint('temperature_c IS NULL OR temperature_c BETWEEN -60 AND 90', name='chk_reading_temp_range'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cargo_readings', schema=None) as batch_op:
        batch_op.create_index('ix_readings_shipment_time', ['shipment_id', 'recorded_at'], unique=False)
        batch_op.create_index('ix_readings_truck_time', ['truck_id', 'recorded_at'], unique=False)
        batch_op.create_index('uq_reading_sensor_client_id', ['sensor_id', 'client_reading_id'], unique=True)

    op.create_table('cold_chain_attestations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('escrow_id', sa.String(length=64), nullable=False),
    sa.Column('shipment_id', sa.String(length=64), nullable=False),
    sa.Column('incident_id', sa.String(length=64), nullable=True),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('required_max_temp_c', sa.Float(), nullable=True),
    sa.Column('readings_count', sa.Integer(), nullable=False),
    sa.Column('min_temp_c', sa.Float(), nullable=True),
    sa.Column('max_temp_c', sa.Float(), nullable=True),
    sa.Column('mean_temp_c', sa.Float(), nullable=True),
    sa.Column('breach_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('breach_minutes', sa.Float(), server_default='0', nullable=False),
    sa.Column('max_gap_minutes', sa.Float(), server_default='0', nullable=False),
    sa.Column('coverage_pct', sa.Float(), server_default='0', nullable=False),
    sa.Column('lowest_trust_level', sa.String(length=16), server_default='UNVERIFIED', nullable=False),
    sa.Column('verdict', sa.String(length=24), nullable=False),
    sa.Column('verdict_reason', sa.String(length=256), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('computed_by', sa.String(length=64), server_default='system', nullable=False),
    sa.Column('evidence_digest', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['escrow_id'], ['escrows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('escrow_id')
    )
    op.create_table('rescue_offers',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('incident_id', sa.String(length=64), nullable=False),
    sa.Column('shipment_id', sa.String(length=64), nullable=False),
    sa.Column('offer_round', sa.Integer(), server_default='1', nullable=False),
    sa.Column('owner_company_id', sa.String(length=64), nullable=False),
    sa.Column('carrier_company_id', sa.String(length=64), nullable=False),
    sa.Column('carrier_truck_id', sa.String(length=64), nullable=False),
    sa.Column('carrier_driver_id', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=32), server_default='PENDING', nullable=False),
    sa.Column('price_total_inr', sa.Float(), nullable=False),
    sa.Column('carrier_payout_inr', sa.Float(), nullable=False),
    sa.Column('platform_fee_inr', sa.Float(), server_default='0', nullable=False),
    sa.Column('price_breakdown_json', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('eta_minutes', sa.Float(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('rescue_score', sa.Float(), nullable=True),
    sa.Column('score_reasons_json', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('carrier_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('carrier_accepted_by', sa.String(length=64), nullable=True),
    sa.Column('owner_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_confirmed_by', sa.String(length=64), nullable=True),
    sa.Column('bound_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('terminal_reason', sa.String(length=48), nullable=True),
    sa.Column('terminal_note', sa.String(length=256), nullable=True),
    sa.Column('terminated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('escrow_id', sa.String(length=64), nullable=True),
    sa.Column('intra_company', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("state IN ('PENDING','CARRIER_ACCEPTED','OWNER_CONFIRMED','BOUND','DECLINED','WITHDRAWN','EXPIRED','SUPERSEDED','CANCELLED')", name='chk_offer_state'),
    sa.CheckConstraint('carrier_payout_inr <= price_total_inr', name='chk_offer_payout_within_price'),
    sa.CheckConstraint('carrier_payout_inr >= 0', name='chk_offer_payout_nonneg'),
    sa.CheckConstraint('price_total_inr >= 0', name='chk_offer_price_nonneg'),
    sa.ForeignKeyConstraint(['carrier_company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['carrier_driver_id'], ['drivers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['carrier_truck_id'], ['trucks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['escrow_id'], ['escrows.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('escrow_id')
    )
    with op.batch_alter_table('rescue_offers', schema=None) as batch_op:
        batch_op.create_index('ix_offers_carrier_inbox', ['carrier_company_id', 'state', 'expires_at'], unique=False)
        batch_op.create_index('ix_offers_expiry_sweep', ['state', 'expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_rescue_offers_carrier_company_id'), ['carrier_company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rescue_offers_carrier_driver_id'), ['carrier_driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rescue_offers_carrier_truck_id'), ['carrier_truck_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rescue_offers_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rescue_offers_owner_company_id'), ['owner_company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rescue_offers_shipment_id'), ['shipment_id'], unique=False)
        batch_op.create_index('uq_offer_bound_per_incident', ['incident_id'], unique=True, sqlite_where=sa.text("state = 'BOUND'"), postgresql_where=sa.text("state = 'BOUND'"))
        batch_op.create_index('uq_offer_incident_truck_round', ['incident_id', 'carrier_truck_id', 'offer_round'], unique=True)
        batch_op.create_index('uq_offer_owner_confirmed_per_incident', ['incident_id'], unique=True, sqlite_where=sa.text("owner_confirmed_at IS NOT NULL AND state IN ('PENDING','CARRIER_ACCEPTED','OWNER_CONFIRMED','BOUND')"), postgresql_where=sa.text("owner_confirmed_at IS NOT NULL AND state IN ('PENDING','CARRIER_ACCEPTED','OWNER_CONFIRMED','BOUND')"))

    op.create_table('shipment_routes',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('shipment_id', sa.String(length=64), nullable=False),
    sa.Column('origin_lat', sa.Float(), nullable=False),
    sa.Column('origin_lng', sa.Float(), nullable=False),
    sa.Column('dest_lat', sa.Float(), nullable=False),
    sa.Column('dest_lng', sa.Float(), nullable=False),
    sa.Column('polyline', sa.Text(), nullable=True),
    sa.Column('corridor_buffer_m', sa.Float(), server_default='3000', nullable=False),
    sa.Column('planned_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=16), server_default='osrm', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipment_routes', schema=None) as batch_op:
        batch_op.create_index('ix_routes_shipment_active', ['shipment_id', 'is_active'], unique=False)

    op.create_table('sos_alerts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('company_id', sa.String(length=64), nullable=False),
    sa.Column('driver_id', sa.String(length=64), nullable=True),
    sa.Column('truck_id', sa.String(length=64), nullable=True),
    sa.Column('shipment_id', sa.String(length=64), nullable=True),
    sa.Column('incident_id', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), server_default='NEW', nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('accuracy_m', sa.Float(), nullable=True),
    sa.Column('location_source', sa.String(length=16), server_default='gps', nullable=False),
    sa.Column('address_text', sa.String(length=256), nullable=True),
    sa.Column('landmark_note', sa.String(length=256), nullable=True),
    sa.Column('persons_affected', sa.Integer(), nullable=True),
    sa.Column('is_conscious', sa.Boolean(), nullable=True),
    sa.Column('is_breathing', sa.Boolean(), nullable=True),
    sa.Column('is_trapped', sa.Boolean(), nullable=True),
    sa.Column('is_mobile', sa.Boolean(), nullable=True),
    sa.Column('severe_bleeding', sa.Boolean(), nullable=True),
    sa.Column('condition_note', sa.String(length=512), nullable=True),
    sa.Column('vitals_json', sa.JSON(), nullable=True),
    sa.Column('driver_medical_snapshot', sa.JSON(), nullable=True),
    sa.Column('medical_shared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('silent_mode', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('broadcast_radius_km', sa.Float(), nullable=False),
    sa.Column('network_broadcast', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('ack_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('responder_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('broadcast_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_ack_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_on_scene_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_escalate_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_code', sa.String(length=32), nullable=True),
    sa.Column('resolution_note', sa.String(length=512), nullable=True),
    sa.Column('created_by_type', sa.String(length=16), nullable=False),
    sa.Column('created_by_id', sa.String(length=64), nullable=False),
    sa.Column('client_request_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("severity IN ('CRITICAL','HIGH','MODERATE')", name='chk_sos_severity'),
    sa.CheckConstraint('latitude BETWEEN -90 AND 90', name='chk_sos_lat_range'),
    sa.CheckConstraint('longitude BETWEEN -180 AND 180', name='chk_sos_lng_range'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sos_alerts', schema=None) as batch_op:
        batch_op.create_index('ix_sos_company_status', ['company_id', 'status', 'received_at'], unique=False)
        batch_op.create_index('ix_sos_status_time', ['status', 'received_at'], unique=False)
        batch_op.create_index('uq_sos_client_request', ['client_request_id'], unique=True)

    op.create_table('telemetry_alerts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('company_id', sa.String(length=64), nullable=False),
    sa.Column('truck_id', sa.String(length=64), nullable=False),
    sa.Column('driver_id', sa.String(length=64), nullable=True),
    sa.Column('shipment_id', sa.String(length=64), nullable=True),
    sa.Column('incident_id', sa.String(length=64), nullable=True),
    sa.Column('alert_type', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='OPEN', nullable=False),
    sa.Column('dedupe_key', sa.String(length=160), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('last_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notify_cooldown_s', sa.Integer(), server_default='900', nullable=False),
    sa.Column('peak_severity', sa.String(length=16), nullable=False),
    sa.Column('first_value_json', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('last_value_json', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('acknowledged_by', sa.String(length=64), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.String(length=256), nullable=True),
    sa.CheckConstraint("severity IN ('INFO','WARN','CRITICAL')", name='chk_alert_severity'),
    sa.CheckConstraint("status IN ('OPEN','ACKNOWLEDGED','RESOLVED','AUTO_RESOLVED')", name='chk_alert_status'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('telemetry_alerts', schema=None) as batch_op:
        batch_op.create_index('ix_alerts_company_status', ['company_id', 'status', 'opened_at'], unique=False)
        batch_op.create_index('ix_alerts_truck_type', ['truck_id', 'alert_type', 'status'], unique=False)
        batch_op.create_index('uq_alert_open_episode', ['dedupe_key'], unique=True, sqlite_where=sa.text("status IN ('OPEN','ACKNOWLEDGED')"), postgresql_where=sa.text("status IN ('OPEN','ACKNOWLEDGED')"))

    op.create_table('telemetry_pings',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('truck_id', sa.String(length=64), nullable=False),
    sa.Column('driver_id', sa.String(length=64), nullable=True),
    sa.Column('company_id', sa.String(length=64), nullable=False),
    sa.Column('shipment_id', sa.String(length=64), nullable=True),
    sa.Column('incident_id', sa.String(length=64), nullable=True),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('client_ping_id', sa.String(length=64), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('accuracy_m', sa.Float(), nullable=True),
    sa.Column('speed_kph', sa.Float(), nullable=True),
    sa.Column('heading_deg', sa.Float(), nullable=True),
    sa.Column('altitude_m', sa.Float(), nullable=True),
    sa.Column('battery_pct', sa.Float(), nullable=True),
    sa.Column('is_charging', sa.Boolean(), nullable=True),
    sa.Column('network_type', sa.String(length=16), nullable=True),
    sa.Column('provider', sa.String(length=16), nullable=True),
    sa.Column('mock_location', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_backfill', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('app_version', sa.String(length=32), nullable=True),
    sa.CheckConstraint('battery_pct IS NULL OR battery_pct BETWEEN 0 AND 100', name='chk_ping_battery_range'),
    sa.CheckConstraint('latitude BETWEEN -90 AND 90', name='chk_ping_lat_range'),
    sa.CheckConstraint('longitude BETWEEN -180 AND 180', name='chk_ping_lng_range'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('telemetry_pings', schema=None) as batch_op:
        batch_op.create_index('ix_pings_company_time', ['company_id', 'recorded_at'], unique=False)
        batch_op.create_index('ix_pings_shipment_time', ['shipment_id', 'recorded_at'], unique=False)
        batch_op.create_index('ix_pings_truck_time', ['truck_id', 'recorded_at'], unique=False)
        batch_op.create_index('uq_ping_device_client_id', ['device_id', 'client_ping_id'], unique=True)

    op.create_table('rescue_ratings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('offer_id', sa.String(length=64), nullable=False),
    sa.Column('incident_id', sa.String(length=64), nullable=False),
    sa.Column('rater_role', sa.String(length=16), nullable=False),
    sa.Column('rater_company_id', sa.String(length=64), nullable=False),
    sa.Column('subject_company_id', sa.String(length=64), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('tags_json', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('comment', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("rater_role IN ('owner','carrier')", name='chk_rating_rater_role'),
    sa.CheckConstraint('stars BETWEEN 1 AND 5', name='chk_rating_stars_range'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['offer_id'], ['rescue_offers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rater_company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rescue_ratings', schema=None) as batch_op:
        batch_op.create_index('ix_ratings_subject', ['subject_company_id', 'created_at'], unique=False)
        batch_op.create_index('uq_rating_offer_rater', ['offer_id', 'rater_role'], unique=True)

    op.create_table('sos_broadcasts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('sos_id', sa.String(length=64), nullable=False),
    sa.Column('recipient_company_id', sa.String(length=64), nullable=False),
    sa.Column('recipient_driver_id', sa.String(length=64), nullable=True),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('adapter_name', sa.String(length=48), server_default='-', nullable=False),
    sa.Column('redaction_level', sa.String(length=16), nullable=False),
    sa.Column('distance_km_at_send', sa.Float(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('adapter_status', sa.String(length=24), server_default='PENDING', nullable=False),
    sa.Column('adapter_ref', sa.String(length=128), nullable=True),
    sa.Column('error', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['recipient_company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_driver_id'], ['drivers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sos_id'], ['sos_alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sos_broadcasts', schema=None) as batch_op:
        batch_op.create_index('ix_sos_broadcast_recipient', ['recipient_company_id', 'sent_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sos_broadcasts_sos_id'), ['sos_id'], unique=False)
        batch_op.create_index('uq_sos_broadcast_target', ['sos_id', 'recipient_company_id', 'channel', 'adapter_name'], unique=True)

    op.create_table('sos_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('sos_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=True),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('previous_status', sa.String(length=24), nullable=True),
    sa.Column('new_status', sa.String(length=24), nullable=True),
    sa.Column('metadata_json', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sos_id'], ['sos_alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sos_events', schema=None) as batch_op:
        batch_op.create_index('ix_sos_events_sos', ['sos_id', 'created_at'], unique=False)

    op.create_table('sos_responses',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('sos_id', sa.String(length=64), nullable=False),
    sa.Column('responder_company_id', sa.String(length=64), nullable=False),
    sa.Column('responder_driver_id', sa.String(length=64), nullable=True),
    sa.Column('responder_truck_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('eta_minutes', sa.Float(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("action IN ('ACKNOWLEDGE','EN_ROUTE','ON_SCENE','STOOD_DOWN','UNABLE','INFO')", name='chk_sos_response_action'),
    sa.ForeignKeyConstraint(['responder_company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responder_driver_id'], ['drivers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['responder_truck_id'], ['trucks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sos_id'], ['sos_alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sos_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sos_responses_responder_company_id'), ['responder_company_id'], unique=False)
        batch_op.create_index('ix_sos_responses_sos', ['sos_id', 'created_at'], unique=False)

    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origin_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('origin_lng', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('destination_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('destination_lng', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('destination_name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('planned_arrival_at', sa.DateTime(timezone=True), nullable=True))
        # Autogenerate does not emit CHECK constraints for an existing table,
        # so these are written by hand. They catch a transposed lat/lng pair,
        # which otherwise silently places a shipment in the wrong hemisphere.
        batch_op.create_check_constraint(
            'chk_shipment_dest_lat_range',
            'destination_lat IS NULL OR destination_lat BETWEEN -90 AND 90',
        )
        batch_op.create_check_constraint(
            'chk_shipment_dest_lng_range',
            'destination_lng IS NULL OR destination_lng BETWEEN -180 AND 180',
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_constraint('chk_shipment_dest_lng_range', type_='check')
        batch_op.drop_constraint('chk_shipment_dest_lat_range', type_='check')
        batch_op.drop_column('planned_arrival_at')
        batch_op.drop_column('destination_name')
        batch_op.drop_column('destination_lng')
        batch_op.drop_column('destination_lat')
        batch_op.drop_column('origin_lng')
        batch_op.drop_column('origin_lat')

    with op.batch_alter_table('sos_responses', schema=None) as batch_op:
        batch_op.drop_index('ix_sos_responses_sos')
        batch_op.drop_index(batch_op.f('ix_sos_responses_responder_company_id'))

    op.drop_table('sos_responses')
    with op.batch_alter_table('sos_events', schema=None) as batch_op:
        batch_op.drop_index('ix_sos_events_sos')

    op.drop_table('sos_events')
    with op.batch_alter_table('sos_broadcasts', schema=None) as batch_op:
        batch_op.drop_index('uq_sos_broadcast_target')
        batch_op.drop_index(batch_op.f('ix_sos_broadcasts_sos_id'))
        batch_op.drop_index('ix_sos_broadcast_recipient')

    op.drop_table('sos_broadcasts')
    with op.batch_alter_table('rescue_ratings', schema=None) as batch_op:
        batch_op.drop_index('uq_rating_offer_rater')
        batch_op.drop_index('ix_ratings_subject')

    op.drop_table('rescue_ratings')
    with op.batch_alter_table('telemetry_pings', schema=None) as batch_op:
        batch_op.drop_index('uq_ping_device_client_id')
        batch_op.drop_index('ix_pings_truck_time')
        batch_op.drop_index('ix_pings_shipment_time')
        batch_op.drop_index('ix_pings_company_time')

    op.drop_table('telemetry_pings')
    with op.batch_alter_table('telemetry_alerts', schema=None) as batch_op:
        batch_op.drop_index('uq_alert_open_episode', sqlite_where=sa.text("status IN ('OPEN','ACKNOWLEDGED')"), postgresql_where=sa.text("status IN ('OPEN','ACKNOWLEDGED')"))
        batch_op.drop_index('ix_alerts_truck_type')
        batch_op.drop_index('ix_alerts_company_status')

    op.drop_table('telemetry_alerts')
    with op.batch_alter_table('sos_alerts', schema=None) as batch_op:
        batch_op.drop_index('uq_sos_client_request')
        batch_op.drop_index('ix_sos_status_time')
        batch_op.drop_index('ix_sos_company_status')

    op.drop_table('sos_alerts')
    with op.batch_alter_table('shipment_routes', schema=None) as batch_op:
        batch_op.drop_index('ix_routes_shipment_active')

    op.drop_table('shipment_routes')
    with op.batch_alter_table('rescue_offers', schema=None) as batch_op:
        batch_op.drop_index('uq_offer_owner_confirmed_per_incident', sqlite_where=sa.text("owner_confirmed_at IS NOT NULL AND state IN ('PENDING','CARRIER_ACCEPTED','OWNER_CONFIRMED','BOUND')"), postgresql_where=sa.text("owner_confirmed_at IS NOT NULL AND state IN ('PENDING','CARRIER_ACCEPTED','OWNER_CONFIRMED','BOUND')"))
        batch_op.drop_index('uq_offer_incident_truck_round')
        batch_op.drop_index('uq_offer_bound_per_incident', sqlite_where=sa.text("state = 'BOUND'"), postgresql_where=sa.text("state = 'BOUND'"))
        batch_op.drop_index(batch_op.f('ix_rescue_offers_shipment_id'))
        batch_op.drop_index(batch_op.f('ix_rescue_offers_owner_company_id'))
        batch_op.drop_index(batch_op.f('ix_rescue_offers_incident_id'))
        batch_op.drop_index(batch_op.f('ix_rescue_offers_carrier_truck_id'))
        batch_op.drop_index(batch_op.f('ix_rescue_offers_carrier_driver_id'))
        batch_op.drop_index(batch_op.f('ix_rescue_offers_carrier_company_id'))
        batch_op.drop_index('ix_offers_expiry_sweep')
        batch_op.drop_index('ix_offers_carrier_inbox')

    op.drop_table('rescue_offers')
    op.drop_table('cold_chain_attestations')
    with op.batch_alter_table('cargo_readings', schema=None) as batch_op:
        batch_op.drop_index('uq_reading_sensor_client_id')
        batch_op.drop_index('ix_readings_truck_time')
        batch_op.drop_index('ix_readings_shipment_time')

    op.drop_table('cargo_readings')
    with op.batch_alter_table('truck_live_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_truck_live_state_company_id'))
        batch_op.drop_index('ix_live_state_received')

    op.drop_table('truck_live_state')
    with op.batch_alter_table('emergency_contacts', schema=None) as batch_op:
        batch_op.drop_index('ix_contacts_scope')

    op.drop_table('emergency_contacts')
    op.drop_table('company_reputation')
    # ### end Alembic commands ###
