"""flag suspect positions instead of discarding them

Revision ID: 0008_suspect_positions
Revises: 0007_offers_telemetry_sos
Create Date: 2026-09-19 01:25:48.985687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0008_suspect_positions'
down_revision: Union[str, None] = '0007_offers_telemetry_sos'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('truck_live_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position_suspect', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('suspect_reason', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('truck_live_state', schema=None) as batch_op:
        batch_op.drop_column('suspect_reason')
        batch_op.drop_column('position_suspect')

    # ### end Alembic commands ###
